# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsonapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='abv',
            field=models.IntegerField(default=0),
        ),
    ]
