# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 23:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jsonapi', '0002_beer_abv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jsonapi.Beer')),
            ],
        ),
    ]
