# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-09 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsonapi', '0004_auto_20161209_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='content',
            field=models.TextField(),
        ),
    ]
