# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-09 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jsonapi', '0005_auto_20161209_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscomment',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newscomment',
            name='news_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='jsonapi.NewsItem'),
        ),
    ]
