# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-09 09:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jsonapi', '0006_auto_20161209_1031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newscomment',
            old_name='text',
            new_name='content',
        ),
    ]
