# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-10 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsonapi', '0007_auto_20161209_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='preamble',
            field=models.TextField(default='ingress'),
            preserve_default=False,
        ),
    ]
