# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-10 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsonapi', '0009_auto_20161211_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
