# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 08:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jsonapi', '0011_auto_20161216_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='jsonapi.NewsComment'),
        ),
    ]
