# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-28 23:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jsonapi', '0016_auto_20161220_2159'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeerBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abv', models.IntegerField(default=0)),
                ('untappd_url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BeerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BrewingSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='BrewingSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('evaporation_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('conversion_efficiency', models.IntegerField(default=100, verbose_name='conversion efficiency (%)')),
                ('lauter_efficiency', models.IntegerField(default=100, verbose_name='lautering efficienct (%)')),
            ],
        ),
        migrations.CreateModel(
            name='Hops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('alpha', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('hops_type', models.CharField(choices=[('cones', 'Cones'), ('pellets', 'Pellets')], default='cones', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Malt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('ebc', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('dbfg', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('mc', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('protein', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='MaltType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('extract_potential', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Yeast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('fermentation_temp_min', models.IntegerField(default=0)),
                ('fermentation_temp_max', models.IntegerField(default=0)),
                ('ideal_temp_min', models.IntegerField(default=0)),
                ('ideal_temp_max', models.IntegerField(default=0)),
                ('alcohol_tolerance', models.IntegerField(default=0)),
                ('yeast_type', models.CharField(choices=[('dry', 'Dry'), ('liquid', 'Liquid')], default='dry', max_length=10)),
                ('attenuation', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('cell_concentration', models.DecimalField(decimal_places=3, default=0, max_digits=5, verbose_name='billion cells/g')),
                ('flocculation', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='beer',
            name='abv',
        ),
        migrations.RemoveField(
            model_name='beer',
            name='untappd_url',
        ),
        migrations.AddField(
            model_name='recipe',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='is_boil_in_bag',
            field=models.BooleanField(default=False, verbose_name='is boil in bag brewing'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='lautering_temp',
            field=models.IntegerField(default=0, verbose_name='lautering temperature'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='mash_in_temp',
            field=models.IntegerField(default=0, verbose_name='mash in temperature'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='mash_out_temp',
            field=models.IntegerField(default=0, verbose_name='mash out temperature'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='mash_out_time',
            field=models.IntegerField(default=0, verbose_name='mash out time'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='mashing_temp',
            field=models.IntegerField(default=0, verbose_name='mashing temperature'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='mashing_time',
            field=models.IntegerField(default=0, verbose_name='mashing time'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='pre_boil_volume',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='start water volume'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='beer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapi.Beer'),
        ),
        migrations.AddField(
            model_name='malt',
            name='malt_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapi.MaltType'),
        ),
        migrations.AddField(
            model_name='brewingsession',
            name='beer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='jsonapi.Beer'),
        ),
        migrations.AddField(
            model_name='brewingsession',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='jsonapi.Recipe'),
        ),
        migrations.AddField(
            model_name='beer',
            name='beer_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jsonapi.BeerType'),
            preserve_default=False,
        ),
    ]
