# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-28 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsonapi', '0017_auto_20161229_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beer',
            name='image_name',
            field=models.CharField(default='dummy.gif', max_length=30),
        ),
    ]
