# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-30 15:01
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jsonapi', '0018_auto_20161229_0050'),
    ]

    operations = [
        migrations.CreateModel(
            name='HopsRecipeEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('add_time', models.IntegerField(default=0)),
                ('hops', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapi.Hops')),
            ],
        ),
        migrations.CreateModel(
            name='MaltRecipeEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('malt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapi.Malt')),
            ],
        ),
        migrations.CreateModel(
            name='MiscIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MiscIngredientEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('add_time', models.IntegerField(default=0)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapi.MiscIngredient')),
            ],
        ),
        migrations.RemoveField(
            model_name='brewingsession',
            name='beer',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='is_boil_in_bag',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='lautering_temp',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='mash_in_temp',
        ),
        migrations.AddField(
            model_name='beerbatch',
            name='session',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='beer_batch', to='jsonapi.BrewingSession'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brewingsession',
            name='fermentation_volume',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='volume in fermentation vessel'),
        ),
        migrations.AddField(
            model_name='brewingsession',
            name='post_boil_volume',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='measured post boil volume'),
        ),
        migrations.AddField(
            model_name='brewingsession',
            name='pre_boil_volume',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='measured pre boil volume'),
        ),
        migrations.AddField(
            model_name='brewingsession',
            name='sparge_water_temp',
            field=models.IntegerField(default=0, verbose_name='measured sparge water temperature'),
        ),
        migrations.AddField(
            model_name='brewingsession',
            name='sparge_water_volume',
            field=models.IntegerField(default=0, verbose_name='measured sparge water volume'),
        ),
        migrations.AddField(
            model_name='brewingsession',
            name='strike_water_temp',
            field=models.IntegerField(default=0, verbose_name='measured strike water temperature'),
        ),
        migrations.AddField(
            model_name='brewingsession',
            name='strike_water_volume',
            field=models.IntegerField(default=0, verbose_name='measured strike water volume'),
        ),
        migrations.AddField(
            model_name='brewingsession',
            name='wort_rest_time',
            field=models.IntegerField(default=0, verbose_name='time to rest the wort'),
        ),
        migrations.AddField(
            model_name='brewingsession',
            name='yeast_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='actual amount of yeast'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='primary_fermentation_temp',
            field=models.IntegerField(default=0, verbose_name='primary fermentation temp (C)'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='primary_fermentation_time',
            field=models.IntegerField(default=0, verbose_name='primary fermentation time (days)'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='sparge_count',
            field=models.IntegerField(default=1, verbose_name='number of sparges'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='sparge_water_temp',
            field=models.IntegerField(default=0, verbose_name='sparge water temperature'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='target_pitch_rate',
            field=models.DecimalField(choices=[(Decimal('0.34999999999999997779553950749686919152736663818359375'), 'Manufacturer'), (Decimal('0.5'), 'Manufacturer 1.060+'), (Decimal('0.75'), 'Ale'), (Decimal('1'), 'Ale 1.060+'), (Decimal('1.5'), 'Lager'), (Decimal('2'), 'Lager 1.060+')], decimal_places=2, default=0.75, max_digits=4),
        ),
        migrations.AddField(
            model_name='recipe',
            name='yeast',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jsonapi.Yeast'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='yeast_amount',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='amount of yeast (g)'),
        ),
        migrations.AlterField(
            model_name='beer',
            name='beer_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beers_of_type', to='jsonapi.BeerType'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='beer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='jsonapi.Beer'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='pre_boil_volume',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='pre boil volume'),
        ),
        migrations.AddField(
            model_name='miscingrediententry',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='misc_entries', to='jsonapi.Recipe'),
        ),
        migrations.AddField(
            model_name='maltrecipeentry',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='malt_entries', to='jsonapi.Recipe'),
        ),
        migrations.AddField(
            model_name='hopsrecipeentry',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hops_entries', to='jsonapi.Recipe'),
        ),
    ]
