# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-02 22:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jsonapi', '0019_auto_20161230_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='brewingsession',
            name='brewing_system',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jsonapi.BrewingSystem'),
            preserve_default=False,
        ),
    ]
