# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-03 17:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jsonapi', '0020_brewingsession_brewing_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoilIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('alpha', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('ingredient_type', models.CharField(choices=[('cones', 'Cones'), ('pellets', 'Pellets'), ('other', 'Other')], default='cones', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='BoilRecipeEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('add_time', models.IntegerField(default=0)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapi.BoilIngredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boil_entries', to='jsonapi.Recipe')),
            ],
        ),
        migrations.CreateModel(
            name='MashRecipeEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, default=0, max_digits=5)),
            ],
        ),
        migrations.RenameModel(
            old_name='Malt',
            new_name='MashIngredient',
        ),
        migrations.RenameModel(
            old_name='MaltType',
            new_name='MashIngredientType',
        ),
        migrations.RemoveField(
            model_name='hopsrecipeentry',
            name='hops',
        ),
        migrations.RemoveField(
            model_name='hopsrecipeentry',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='maltrecipeentry',
            name='malt',
        ),
        migrations.RemoveField(
            model_name='maltrecipeentry',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='miscingrediententry',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='miscingrediententry',
            name='recipe',
        ),
        migrations.RenameField(
            model_name='mashingredient',
            old_name='malt_type',
            new_name='ingredient_type',
        ),
        migrations.DeleteModel(
            name='Hops',
        ),
        migrations.DeleteModel(
            name='HopsRecipeEntry',
        ),
        migrations.DeleteModel(
            name='MaltRecipeEntry',
        ),
        migrations.DeleteModel(
            name='MiscIngredient',
        ),
        migrations.DeleteModel(
            name='MiscIngredientEntry',
        ),
        migrations.AddField(
            model_name='mashrecipeentry',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapi.MashIngredient'),
        ),
        migrations.AddField(
            model_name='mashrecipeentry',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mash_entries', to='jsonapi.Recipe'),
        ),
    ]
