# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-03 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsonapi', '0021_auto_20170103_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='mashingredienttype',
            name='is_malt',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mashrecipeentry',
            name='amount',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='amount of malt in %'),
        ),
    ]
