# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-04 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsonapi', '0022_auto_20170104_0008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='sparge_water_temp',
        ),
        migrations.AddField(
            model_name='recipe',
            name='water_to_malt_ratio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='water to malt ratio'),
        ),
    ]
