# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-04 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsonapi', '0025_recipe_sparge_water_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='water_to_malt_ratio',
        ),
        migrations.AddField(
            model_name='recipe',
            name='total_malt_weight',
            field=models.DecimalField(decimal_places=1, default=5, max_digits=4, verbose_name='total malt weight'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='pre_boil_volume',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=4, verbose_name='pre boil volume'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='sparge_water_temp',
            field=models.IntegerField(default=73, verbose_name='sparge water temperature'),
        ),
    ]
