# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-06 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsonapi', '0026_auto_20170104_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='brewingsystem',
            name='boiler_dead_space',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='dead space when transfering to fermentor'),
        ),
        migrations.AddField(
            model_name='brewingsystem',
            name='transfer_loss',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='loss due to transfer to boiler'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='boil_time',
            field=models.IntegerField(default=60, verbose_name='time to boil in minutes'),
        ),
        migrations.AlterField(
            model_name='boilingredient',
            name='ingredient_type',
            field=models.CharField(choices=[('cones', 'Hops Cones'), ('pellets', 'Hops Pellets'), ('other', 'Other')], default='cones', max_length=10),
        ),
        migrations.AlterField(
            model_name='boilrecipeentry',
            name='add_time',
            field=models.IntegerField(default=0, verbose_name='time to add from start of boil'),
        ),
        migrations.AlterField(
            model_name='boilrecipeentry',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='amount in grams'),
        ),
        migrations.AlterField(
            model_name='brewingsystem',
            name='evaporation_rate',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='evaporation rate in l/hour'),
        ),
    ]
