# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-14 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jsonapi', '0027_auto_20170107_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brewingsession',
            name='brewing_system',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jsonapi.BrewingSystem'),
        ),
        migrations.AlterField(
            model_name='yeast',
            name='attenuation',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='attenuation in %'),
        ),
    ]
