# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-18 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsonapi', '0028_auto_20170114_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brewingsession',
            name='sparge_water_volume',
        ),
        migrations.RemoveField(
            model_name='brewingsession',
            name='strike_water_volume',
        ),
        migrations.RemoveField(
            model_name='brewingsession',
            name='wort_rest_time',
        ),
        migrations.AddField(
            model_name='boilingredient',
            name='extract',
            field=models.IntegerField(default=0, verbose_name='sugar content in %'),
        ),
        migrations.AddField(
            model_name='brewingsession',
            name='wort_settle_time',
            field=models.IntegerField(default=0, verbose_name='time to let the sediment settle in the wort'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='post_boil_volume',
            field=models.DecimalField(decimal_places=2, default=15, max_digits=4, verbose_name='post boil volume'),
        ),
        migrations.AlterField(
            model_name='brewingsystem',
            name='lauter_efficiency',
            field=models.IntegerField(default=100, verbose_name='lautering efficiency (%)'),
        ),
    ]
