# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-18 21:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jsonapi', '0030_recipe_fermentation_volume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brewingsystem',
            old_name='evaporation_rate',
            new_name='boil_off_rate',
        ),
    ]
