# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-18 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsonapi', '0031_auto_20170118_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brewingsession',
            name='yeast_amount',
        ),
        migrations.AddField(
            model_name='brewingsession',
            name='fg',
            field=models.DecimalField(decimal_places=3, default=1.0, max_digits=4, verbose_name='measured fg'),
        ),
        migrations.AddField(
            model_name='brewingsession',
            name='first_sparge_sg',
            field=models.DecimalField(decimal_places=3, default=1.0, max_digits=4, verbose_name='measured first sparge sg'),
        ),
        migrations.AddField(
            model_name='brewingsession',
            name='first_wort_sg',
            field=models.DecimalField(decimal_places=3, default=1.0, max_digits=4, verbose_name='measured first wort sg'),
        ),
        migrations.AddField(
            model_name='brewingsession',
            name='og',
            field=models.DecimalField(decimal_places=3, default=1.0, max_digits=4, verbose_name='measured og'),
        ),
        migrations.AddField(
            model_name='brewingsession',
            name='pre_boil_sg',
            field=models.DecimalField(decimal_places=3, default=1.0, max_digits=4, verbose_name='measured pre boil sg'),
        ),
        migrations.AddField(
            model_name='brewingsession',
            name='yeast_used',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='amount of yeast used'),
        ),
    ]
