# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-18 22:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jsonapi', '0032_auto_20170118_2320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brewingsession',
            old_name='fg',
            new_name='measured_fg',
        ),
        migrations.RenameField(
            model_name='brewingsession',
            old_name='first_sparge_sg',
            new_name='measured_first_sparge_sg',
        ),
        migrations.RenameField(
            model_name='brewingsession',
            old_name='first_wort_sg',
            new_name='measured_first_wort_sg',
        ),
        migrations.RenameField(
            model_name='brewingsession',
            old_name='og',
            new_name='measured_og',
        ),
        migrations.RenameField(
            model_name='brewingsession',
            old_name='pre_boil_sg',
            new_name='measured_pre_boil_sg',
        ),
    ]
