# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jsonapi', '0033_auto_20170118_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='PitchType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pitch_rate', models.DecimalField(decimal_places=2, default=1.0, max_digits=6, verbose_name='billion cells/l wort/plato')),
            ],
        ),
        migrations.AlterField(
            model_name='recipe',
            name='target_pitch_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapi.PitchType'),
        ),
    ]
