# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jsonapi', '0035_auto_20170119_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='pitch_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jsonapi.PitchType'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='yeast',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jsonapi.Yeast'),
        ),
    ]
