# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsonapi', '0036_auto_20170119_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='beertype',
            name='priming_co2_volume_max',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='max CO2 volume for priming'),
        ),
        migrations.AddField(
            model_name='beertype',
            name='priming_co2_volume_min',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='min CO2 volume for priming'),
        ),
    ]
