# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-22 11:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jsonapi', '0038_auto_20170119_2254'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoilSessionEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alpha', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('recipe_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapi.BoilRecipeEntry')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boil_entries', to='jsonapi.BrewingSession')),
            ],
        ),
    ]
