# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-22 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsonapi', '0039_boilsessionentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boilrecipeentry',
            name='add_time',
        ),
        migrations.AddField(
            model_name='boilrecipeentry',
            name='boil_time',
            field=models.IntegerField(default=0, verbose_name='time to boil in mins'),
        ),
    ]
