# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-10-21 16:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jsonapi', '0040_auto_20170122_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrewingSessionComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('brewing_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='jsonapi.BrewingSession')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='jsonapi.BrewingSessionComment')),
            ],
        ),
    ]
