# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-10-23 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsonapi', '0042_auto_20171021_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='sparge_time',
            field=models.IntegerField(default=20, verbose_name='sparge time'),
        ),
    ]
