# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-10-30 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsonapi', '0046_auto_20171030_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='brewingsession',
            name='boil_time',
            field=models.IntegerField(default=60, verbose_name='time to boil in minutes'),
        ),
    ]
