# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-10-30 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsonapi', '0047_brewingsession_boil_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='boilsessionentry',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='scale adjusted amount in grams'),
        ),
    ]
