# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-11-19 18:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jsonapi', '0050_auto_20171105_1629'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'permissions': (('view_recipe', 'Can view recipe'),)},
        ),
    ]
