# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-11-22 19:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jsonapi', '0051_auto_20171119_1921'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brewingsession',
            options={'permissions': (('view_brewingsession', 'Can view brewing session'),)},
        ),
    ]
