# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-11-28 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsonapi', '0052_auto_20171122_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='brewingsession',
            name='sugar_used',
            field=models.IntegerField(default=0, verbose_name='amount of sugar used (g)'),
        ),
    ]
